#!/usr/bin/env bash

git fetch

git checkout gh-pages

git merge master --no-commit

npm install

node_modules/rhyme/data/fetch.sh

npm run bundle

git commit -am "Update bundle"

git push origin gh-pages

git checkout -
